plugins:
  - name: proxy-rewrite
  - name: key-auth

consumers:
  - username: default
    plugins:
      key-auth:
        key: "default"
  - username: default2
    plugins:
      key-auth:
        key: "default2"

routes:
  - uri: /prism-agent/*
    upstream_id: 4
    plugins:
      proxy-rewrite:
        regex_uri: ["^/prism-agent/(.*)", "/$1"]
#      key-auth: {}
  - uri: /docs/prism-agent/api/*
    upstream_id: 4
    plugins:
      proxy-rewrite:
        regex_uri: ["^/docs/prism-agent/api/(.*)", "/docs/$1"]
#      key-auth: {}
  - uri: /didcomm*
    upstream_id: 3
    plugins:
      proxy-rewrite:
        regex_uri: ["^/didcomm(.*)", "/$1"]
  - uri: /mediator/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri: ["^/mediator/(.*)", "/$1"]
      key-auth: {}
  - uri: /docs/mediator/api/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri: ["^/docs/mediator/api/(.*)", "/api/$1"]
  - uri: /apidocs/*
    upstream_id: 5
    plugins:
      proxy-rewrite:
        regex_uri: ["^/apidocs/(.*)", "/$1"]

upstreams:
  - id: 1
    nodes:
      "mediator:8080": 1
    type: roundrobin
  - id: 3
    nodes:
      "prism-agent:8090": 1 # didcom and system
    type: roundrobin
  - id: 4
    nodes:
      "prism-agent:8085": 1 # tapir
    type: roundrobin
  - id: 5
    nodes:
      "swagger-ui:8080": 1
    type: roundrobin
#END
