# Configuration file for Mega-Linter
# See all available variables at https://megalinter.github.io/configuration/

APPLY_FIXES: all
DEFAULT_BRANCH: main
FAIL_IF_UPDATED_SOURCES: true
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - DOCKERFILE_HADOLINT
  - REPOSITORY_TRIVY
  - REPOSITORY_CHECKOV
  - REPOSITORY_SECRETLINT
  - REPOSITORY_KICS
  - REPOSITORY_GRYPE
  - SCALA_SCALAFIX
  - SQL_TSQLLINT
  - C_CPPLINT # For pollux/lib/anoncreds/src/main/c
  - CPP_CPPLINT # For pollux/lib/anoncreds/src/main/c
  - JAVA_CHECKSTYLE # For pollux/lib/anoncreds/src/main/java
  - GHERKIN_GHERKIN_LINT
  - OPENAPI_SPECTRAL
  # For python, disable all except PYTHON_BLACK linter
  - PYTHON_PYLINT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_RUFF

DISABLE_ERRORS_LINTERS:
  - KOTLIN_KTLINT
  - KOTLIN_DETEKT
  - PROTOBUF_PROTOLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - ACTION_ACTIONLINT

DISABLE: [COPYPASTE, SPELL, CREDENTIALS]
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
VALIDATE_ALL_CODEBASE: false
SHOW_SKIPPED_LINTERS: false
LOG_LEVEL: INFO
BASH_SHELLCHECK_DISABLE_ERRORS: true
# This pre-command fixes complex CLRF bug
# when MegaLinter takes changes, it checkouts code twice
# that could lead to new files in workspace created
# with CLRF instead of CL due docker/python/git chain
PRE_COMMANDS:
  - command: git config --global core.autocrlf input
    cwd: "workspace"
  - command: pip install Click==8.1.3
    cwd: "workspace"

# Linter customisation
MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: CHANGELOG\.md|DEPENDENCIES\.md
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: CHANGELOG\.md|DEPENDENCIES\.md
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: CHANGELOG\.md|DEPENDENCIES\.md
SQL_SQL_LINT_ARGUMENTS: -d postgres --ignore-errors=postgres-invalid-alter-option,postgres-invalid-create-option,postgres-invalid-drop-option
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "infrastructure/charts/agent/*|cloud-agent/service/api/http/*|examples/*"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "infrastructure/charts/agent/*|cloud-agent/service/api/http/*|examples/*"
YAML_V8R_FILTER_REGEX_EXCLUDE: "infrastructure/charts/agent/*"
JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE:
  "tests/performance-tests/agent-performance-tests-k6/src/k6chaijs.js\
  |tests/didcomm-tests/docker/initdb.js"
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: "infrastructure/*"
