/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.hyperledger.identus.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dateTime 
 */


data class DateTimeParameter : VcVerificationParameter(dateTime, null) (

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime

)

