/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package org.hyperledger.identus.client.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param dateTime
 * @param parameterType
 */

data class DateTimeParameter(

    @SerializedName("did")
    override val did: kotlin.String? = null,

    @SerializedName("parameterType")
    override val parameterType: kotlin.String = "DateTimeParameter",

    @SerializedName("dateTime")
    override val dateTime: java.time.OffsetDateTime,

) : VcVerificationParameter
