/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "RemoveRedundantQualifierName",
)

package org.hyperledger.identus.client.models

import com.google.gson.Gson
import com.google.gson.annotations.SerializedName
import org.hyperledger.identus.client.custom.types.JsonType
import org.hyperledger.identus.client.custom.types.ServiceType

/**
 * The service endpoint. Can contain multiple possible values as described in the [Create DID operation](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md#create-did)
 */
class Json(
    @SerializedName("value") val value: JsonType?
)

fun serviceType() {
//    val string = """{"id": "id", "type":"type-string",  "serviceEndpoint": "endpoint-string"}"""
    val array = """{"id": "id", "type":["type-array"],  "serviceEndpoint": ["endpoint-array"]}"""

//    println(Gson().fromJson(string, Service::class.java))
    println(Gson().fromJson(array, Service::class.java))
}

fun jsonType1() {
    val string = """{"value":"ex"}"""
    val array = """{"value":["a","b"]}"""
    val number = """{"value":3}"""
    val bool = """{"value":false}"""
    val obj = """{"value":{"p":"works"}}"""
    val nullable = """{"value":null}"""

    println(Gson().fromJson(string, Json::class.java).value?.asString())
    println(Gson().fromJson(array, Json::class.java).value?.asArray())
    println(Gson().fromJson(number, Json::class.java).value?.asNumber())
    println(Gson().fromJson(bool, Json::class.java).value?.asBool())
    println(Gson().fromJson(obj, Json::class.java).value?.asObject(X::class))
    println(Gson().fromJson(nullable, Json::class.java).value?.asString())
}

data class X(
    val p: String
)

fun main() {
    println("== Service type")
    serviceType()

    println("== Json type")
    jsonType1()
}
