/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.hyperledger.identus.client.models

import com.google.gson.annotations.SerializedName
import com.google.gson.JsonElement
import com.google.gson.JsonPrimitive


/**
 * A service expressed in the DID document. https://www.w3.org/TR/did-core/#services
 *
 * @param id The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID
 * @param type 
 * @param serviceEndpoint 
 */


data class Service (

    /* The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID */
    @SerializedName("id")
    val id: kotlin.String,

    @SerializedName("type")
    val type: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("serviceEndpoint")
    val serviceEndpoint: JsonElement? = null

)

fun main() {
    val service = Service(
        id = "id",
        type = listOf("type"),
        serviceEndpoint = JsonPrimitive("https://example.com")
    )
    println(service)
}

