/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.hyperledger.identus.client.models

import com.google.gson.Gson
import com.google.gson.TypeAdapter
import com.google.gson.annotations.JsonAdapter

import com.google.gson.annotations.SerializedName
import com.google.gson.reflect.TypeToken
import com.google.gson.stream.JsonReader
import com.google.gson.stream.JsonWriter
import org.hyperledger.identus.client.custom.parse
import org.hyperledger.identus.client.custom.types.JsonType
import org.hyperledger.identus.client.custom.types.ServiceType

/**
 * A service expressed in the DID document. https://www.w3.org/TR/did-core/#services
 *
 * @param id The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID
 * @param type
 * @param serviceEndpoint
 */

class Service(
    /* The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID */
    @SerializedName("id") val id: String,
    @SerializedName("type") val type: ServiceType,
    @SerializedName("serviceEndpoint") val serviceEndpoint: JsonType
)
