/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.hyperledger.identus.client.models

import org.hyperledger.identus.client.models.DateTimeParameter
import org.hyperledger.identus.client.models.DidParameter

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dateTime 
 * @param aud 
 */


open class VcVerificationParameter (

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime? = null,

    @SerializedName("aud")
    val aud: kotlin.String? = null
)

