/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package org.hyperledger.identus.client.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param dateTime
 * @param parameterType
 * @param did
 */

interface VcVerificationParameter {

    @get:SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime?

    @get:SerializedName("parameterType")
    val parameterType: kotlin.String

    @get:SerializedName("did")
    val did: kotlin.String?
}
