components:
  parameters:
    connectionId:
      in: path
      name: connectionId
      required: true
      description: The unique identifier of the connection record.
      schema:
        type: string