{{- if .Values.ingress.enabled }}
{{- $root := . -}}
{{- range $consumer := .Values.consumers }}
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "{{ $root.Release.Namespace }}-{{ $consumer | lower }}"
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{ template "labels.common" . }}
spec:
  forceRegenerate: false
  data:
    username: {{ $consumer | lower }}
  fields:
    - fieldName: "key"
      encoding: "base64"
      length: "32"
{{- end }}
{{- end }}
