name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: self-hosted
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.ATALA_GITHUB_TOKEN }}"
