/**
 * Identus Cloud Agent API Reference
 *  The Identus Cloud Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent) 
 *
 * OpenAPI spec version: 1.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CwtProof } from '../models/CwtProof';
import { JwtProof } from '../models/JwtProof';
import { LdpProof } from '../models/LdpProof';
import { ProofType } from '../models/ProofType';
import { HttpFile } from '../http/http';

export class Proof2 {
    'proofType': ProofType;
    'cwt': string;
    'jwt': string;
    'vp': string;

    static readonly discriminator: string | undefined = "proofType";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "proofType",
            "baseName": "proof_type",
            "type": "ProofType",
            "format": ""
        },
        {
            "name": "cwt",
            "baseName": "cwt",
            "type": "string",
            "format": ""
        },
        {
            "name": "jwt",
            "baseName": "jwt",
            "type": "string",
            "format": ""
        },
        {
            "name": "vp",
            "baseName": "vp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Proof2.attributeTypeMap;
    }

    public constructor() {
    }
}



