/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Json } from '../models/Json';

/**
* A patch to existing Service. \'type\' and \'serviceEndpoint\' cannot both be empty.
*/
export class UpdateManagedDIDServiceAction {
    /**
    * The id of the service to update
    */
    'id': string;
    'type'?: Array<string>;
    'serviceEndpoint'?: Json;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpdateManagedDIDServiceActionType",
            "format": ""
        },
        {
            "name": "serviceEndpoint",
            "baseName": "serviceEndpoint",
            "type": "Json",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateManagedDIDServiceAction.attributeTypeMap;
    }
}

