/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invitation The base64-encoded raw invitation.
 */


data class AcceptConnectionInvitationRequest (

    /* The base64-encoded raw invitation. */
    @Json(name = "invitation")
    val invitation: kotlin.String

)

