/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectId The short-form subject Prism DID to which the verifiable credential should be issued.
 */


data class AcceptCredentialOfferRequest (

    /* The short-form subject Prism DID to which the verifiable credential should be issued. */
    @Json(name = "subjectId")
    val subjectId: kotlin.String

)

