/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: aDDKEY,aDDSERVICE,rEMOVEKEY,rEMOVESERVICE,uPDATESERVICE
 */

@JsonClass(generateAdapter = false)
enum class ActionType(val value: kotlin.String) {

    @Json(name = "ADD_KEY")
    aDDKEY("ADD_KEY"),

    @Json(name = "ADD_SERVICE")
    aDDSERVICE("ADD_SERVICE"),

    @Json(name = "REMOVE_KEY")
    rEMOVEKEY("REMOVE_KEY"),

    @Json(name = "REMOVE_SERVICE")
    rEMOVESERVICE("REMOVE_SERVICE"),

    @Json(name = "UPDATE_SERVICE")
    uPDATESERVICE("UPDATE_SERVICE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ActionType) "$data" else null

        /**
         * Returns a valid [ActionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ActionType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

