/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.Connection

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param self 
 * @param pageOf 
 * @param contents 
 * @param next 
 * @param previous 
 */


data class ConnectionsPage (

    /*  */
    @Json(name = "kind")
    val kind: kotlin.String,

    /*  */
    @Json(name = "self")
    val self: kotlin.String,

    /*  */
    @Json(name = "pageOf")
    val pageOf: kotlin.String,

    /*  */
    @Json(name = "contents")
    val contents: kotlin.collections.List<Connection>? = null,

    /*  */
    @Json(name = "next")
    val next: kotlin.String? = null,

    /*  */
    @Json(name = "previous")
    val previous: kotlin.String? = null

)

