/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param longFormDid A long-form DID for the created DID
 */


data class CreateManagedDIDResponse (

    /* A long-form DID for the created DID */
    @Json(name = "longFormDid")
    val longFormDid: kotlin.String

)

