/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.ManagedDIDKeyTemplate
import io.iohk.atala.prism.models.Service

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param publicKeys 
 * @param services 
 */


data class CreateManagedDidRequestDocumentTemplate (

    @Json(name = "publicKeys")
    val publicKeys: kotlin.collections.List<ManagedDIDKeyTemplate>? = null,

    @Json(name = "services")
    val services: kotlin.collections.List<Service>? = null

)

