/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param claims The claims that will be associated with the issued verifiable credential.
 * @param issuingDID The issuer DID of the verifiable credential object.
 * @param connectionId The unique identifier of a DIDComm connection that already exists between the issuer and the holder, and that will be used to execute the issue credential protocol.
 * @param validityPeriod The validity period in seconds of the verifiable credential that will be issued.
 * @param automaticIssuance Specifies whether or not the credential should be automatically generated and issued when receiving the `CredentialRequest` from the holder. If set to `false`, a manual approval by the issuer via API call will be required for the VC to be issued.
 */


data class CreateIssueCredentialRecordRequest (

    /* The claims that will be associated with the issued verifiable credential. */
    @Json(name = "claims")
    val claims: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* The issuer DID of the verifiable credential object. */
    @Json(name = "issuingDID")
    val issuingDID: kotlin.String,

    /* The unique identifier of a DIDComm connection that already exists between the issuer and the holder, and that will be used to execute the issue credential protocol. */
    @Json(name = "connectionId")
    val connectionId: kotlin.String,

    /* The validity period in seconds of the verifiable credential that will be issued. */
    @Json(name = "validityPeriod")
    val validityPeriod: kotlin.Double? = null,

    /* Specifies whether or not the credential should be automatically generated and issued when receiving the `CredentialRequest` from the holder. If set to `false`, a manual approval by the issuer via API call will be required for the VC to be issued. */
    @Json(name = "automaticIssuance")
    val automaticIssuance: kotlin.Boolean? = null

)

