/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name A human-readable name for the credential schema. A piece of Metadata.
 * @param version Denotes the revision of a given Credential Schema. It should follow semantic version convention to describe the impact of the schema evolution.
 * @param type This field resolves to a JSON schema with details about the schema metadata that applies to the schema. A piece of Metadata.
 * @param schema Valid JSON Schema where the Credential Schema data fields are defined. A piece of Metadata
 * @param author DID of the identity which authored the credential schema. A piece of Metadata.
 * @param description A human-readable description of the credential schema
 * @param tags Tokens that allow to lookup and filter the credential schema records.
 */


data class CredentialSchemaInput (

    /* A human-readable name for the credential schema. A piece of Metadata. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Denotes the revision of a given Credential Schema. It should follow semantic version convention to describe the impact of the schema evolution. */
    @Json(name = "version")
    val version: kotlin.String,

    /* This field resolves to a JSON schema with details about the schema metadata that applies to the schema. A piece of Metadata. */
    @Json(name = "type")
    val type: kotlin.String,

    /* Valid JSON Schema where the Credential Schema data fields are defined. A piece of Metadata */
    @Json(name = "schema")
    val schema: kotlin.Any?,

    /* DID of the identity which authored the credential schema. A piece of Metadata. */
    @Json(name = "author")
    val author: kotlin.String,

    /* A human-readable description of the credential schema */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Tokens that allow to lookup and filter the credential schema records. */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

)

