/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import com.google.gson.annotations.SerializedName

/**
 * Object containing claims specific to status list credential
 *
 * @param id Url to resolve this particular status list credential
 * @param type Always equals to constnat value - StatusList2021
 * @param statusPurpose
 * @param encodedList base64 url encoded bitstring of credential statuses
 */


data class CredentialSubject (

    /* Url to resolve this particular status list credential */
    @SerializedName("id")
    val id: kotlin.String,

    /* Always equals to constnat value - StatusList2021 */
    @SerializedName("type")
    val type: kotlin.String,

    @SerializedName("statusPurpose")
    val statusPurpose: String,

    /* base64 url encoded bitstring of credential statuses */
    @SerializedName("encodedList")
    val encodedList: kotlin.String

)

