/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.CredentialSchemaResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind A string field indicating the type of the API response. In this case, it will always be set to `CredentialSchemaPage`
 * @param self A string field containing the URL of the current API endpoint
 * @param pageOf A string field indicating the type of resource that the contents field contains
 * @param contents A sequence of CredentialSchemaResponse objects representing the list of credential schemas that the API response contains
 * @param next An optional string field containing the URL of the next page of results. If the API response does not contain any more pages, this field should be set to None.
 * @param previous An optional string field containing the URL of the previous page of results. If the API response is the first page of results, this field should be set to None.
 */


data class CredentialSchemaResponsePage (

    /* A string field indicating the type of the API response. In this case, it will always be set to `CredentialSchemaPage` */
    @Json(name = "kind")
    val kind: kotlin.String,

    /* A string field containing the URL of the current API endpoint */
    @Json(name = "self")
    val self: kotlin.String,

    /* A string field indicating the type of resource that the contents field contains */
    @Json(name = "pageOf")
    val pageOf: kotlin.String,

    /* A sequence of CredentialSchemaResponse objects representing the list of credential schemas that the API response contains */
    @Json(name = "contents")
    val contents: kotlin.collections.List<CredentialSchemaResponse>? = null,

    /* An optional string field containing the URL of the next page of results. If the API response does not contain any more pages, this field should be set to None. */
    @Json(name = "next")
    val next: kotlin.String? = null,

    /* An optional string field containing the URL of the previous page of results. If the API response is the first page of results, this field should be set to None. */
    @Json(name = "previous")
    val previous: kotlin.String? = null

)

