/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * [DID document metadata](https://www.w3.org/TR/did-core/#did-document-metadata)
 *
 * @param deactivated If a DID has been deactivated, DID document metadata MUST include this property with the boolean value true. If a DID has not been deactivated, this property is OPTIONAL, but if included, MUST have the boolean value false.
 * @param canonicalId  A DID in canonical form. If a DID is in long form and has been published, DID document metadata MUST contain a `canonicalId`` property with the short form DID as its value. If a DID in short form or has not been published, DID document metadata MUST NOT contain a `canonicalId` property. 
 */


data class DIDDocumentMetadata (

    /* If a DID has been deactivated, DID document metadata MUST include this property with the boolean value true. If a DID has not been deactivated, this property is OPTIONAL, but if included, MUST have the boolean value false. */
    @Json(name = "deactivated")
    val deactivated: kotlin.Boolean? = null,

    /*  A DID in canonical form. If a DID is in long form and has been published, DID document metadata MUST contain a `canonicalId`` property with the short form DID as its value. If a DID in short form or has not been published, DID document metadata MUST NOT contain a `canonicalId` property.  */
    @Json(name = "canonicalId")
    val canonicalId: kotlin.String? = null

)

