/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.Service
import io.iohk.atala.prism.models.VerificationMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A W3C compliant Prism DID document representation.
 *
 * @param id [DID subject](https://www.w3.org/TR/did-core/#did-subject). The value must match the DID that was given to the resolver.
 * @param atContext The JSON-LD context for the DID resolution result.
 * @param controller [DID controller](https://www.w3.org/TR/did-core/#did-controller)
 * @param verificationMethod 
 * @param authentication 
 * @param assertionMethod 
 * @param keyAgreement 
 * @param capabilityInvocation 
 * @param capabilityDelegation 
 * @param service 
 */


data class DIDDocument (

    /* [DID subject](https://www.w3.org/TR/did-core/#did-subject). The value must match the DID that was given to the resolver. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The JSON-LD context for the DID resolution result. */
    @Json(name = "@context")
    val atContext: kotlin.collections.List<kotlin.String>? = null,

    /* [DID controller](https://www.w3.org/TR/did-core/#did-controller) */
    @Json(name = "controller")
    val controller: kotlin.String? = null,

    @Json(name = "verificationMethod")
    val verificationMethod: kotlin.collections.List<VerificationMethod>? = null,

    @Json(name = "authentication")
    val authentication: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "assertionMethod")
    val assertionMethod: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "keyAgreement")
    val keyAgreement: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "capabilityInvocation")
    val capabilityInvocation: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "capabilityDelegation")
    val capabilityDelegation: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "service")
    val service: kotlin.collections.List<Service>? = null

)

