/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id A scheduled operation ID
 * @param didRef A DID affected by the scheduled operation
 */


data class DidOperationSubmission (

    /* A scheduled operation ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* A DID affected by the scheduled operation */
    @Json(name = "didRef")
    val didRef: kotlin.String

)

