/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.DIDDocument
import io.iohk.atala.prism.models.DIDDocumentMetadata
import io.iohk.atala.prism.models.DIDResolutionMetadata

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atContext The JSON-LD context for the DID resolution result.
 * @param didDocumentMetadata 
 * @param didResolutionMetadata 
 * @param didDocument 
 */


data class DIDResolutionResult (

    /* The JSON-LD context for the DID resolution result. */
    @Json(name = "@context")
    val atContext: kotlin.String,

    @Json(name = "didDocumentMetadata")
    val didDocumentMetadata: DIDDocumentMetadata,

    @Json(name = "didResolutionMetadata")
    val didResolutionMetadata: DIDResolutionMetadata,

    @Json(name = "didDocument")
    val didDocument: DIDDocument? = null

)

