/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * [DID resolution metadata](https://www.w3.org/TR/did-core/#did-resolution-metadata)
 *
 * @param error Resolution error constant according to [DID spec registries](https://www.w3.org/TR/did-spec-registries/#error)
 * @param errorMessage Resolution error message
 * @param contentType The media type of the returned DID document
 */


data class DIDResolutionMetadata (

    /* Resolution error constant according to [DID spec registries](https://www.w3.org/TR/did-spec-registries/#error) */
    @Json(name = "error")
    val error: kotlin.String? = null,

    /* Resolution error message */
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String? = null,

    /* The media type of the returned DID document */
    @Json(name = "contentType")
    val contentType: kotlin.String? = null

)

