/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status The HTTP status code for this occurrence of the problem.
 * @param type A URI reference that identifies the problem type.
 * @param title A short, human-readable summary of the problem type. It does not change from occurrence to occurrence of the problem.
 * @param instance A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
 * @param detail A human-readable explanation specific to this occurrence of the problem.
 */


data class ErrorResponse (

    /* The HTTP status code for this occurrence of the problem. */
    @Json(name = "status")
    val status: kotlin.Int,

    /* A URI reference that identifies the problem type. */
    @Json(name = "type")
    val type: kotlin.String,

    /* A short, human-readable summary of the problem type. It does not change from occurrence to occurrence of the problem. */
    @Json(name = "title")
    val title: kotlin.String,

    /* A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
    @Json(name = "instance")
    val instance: kotlin.String,

    /* A human-readable explanation specific to this occurrence of the problem. */
    @Json(name = "detail")
    val detail: kotlin.String? = null

)

