/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param claims The claims that will be associated with the issued verifiable credential.
 * @param recordId The unique identifier of the issue credential record.
 * @param createdAt The date and time when the issue credential record was created.
 * @param role The role played by the Prism agent in the credential issuance flow.
 * @param protocolState The current state of the issue credential protocol execution.
 * @param subjectId The identifier (e.g DID) of the subject to which the verifiable credential will be issued.
 * @param validityPeriod The validity period in seconds of the verifiable credential that will be issued.
 * @param automaticIssuance Specifies whether or not the credential should be automatically generated and issued when receiving the `CredentialRequest` from the holder. If set to `false`, a manual approval by the issuer via API call will be required for the VC to be issued.
 * @param updatedAt The date and time when the issue credential record was last updated.
 * @param jwtCredential The base64-encoded JWT verifiable credential that has been sent by the issuer.
 * @param issuingDID Issuer DID of the verifiable credential object.
 */


data class IssueCredentialRecord (

    /* The claims that will be associated with the issued verifiable credential. */
    @Json(name = "claims")
    val claims: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* The unique identifier of the issue credential record. */
    @Json(name = "recordId")
    val recordId: kotlin.String,

    /* The date and time when the issue credential record was created. */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* The role played by the Prism agent in the credential issuance flow. */
    @Json(name = "role")
    val role: kotlin.String,

    /* The current state of the issue credential protocol execution. */
    @Json(name = "protocolState")
    val protocolState: kotlin.String,

    /* The identifier (e.g DID) of the subject to which the verifiable credential will be issued. */
    @Json(name = "subjectId")
    val subjectId: kotlin.String? = null,

    /* The validity period in seconds of the verifiable credential that will be issued. */
    @Json(name = "validityPeriod")
    val validityPeriod: kotlin.Double? = null,

    /* Specifies whether or not the credential should be automatically generated and issued when receiving the `CredentialRequest` from the holder. If set to `false`, a manual approval by the issuer via API call will be required for the VC to be issued. */
    @Json(name = "automaticIssuance")
    val automaticIssuance: kotlin.Boolean? = null,

    /* The date and time when the issue credential record was last updated. */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    /* The base64-encoded JWT verifiable credential that has been sent by the issuer. */
    @Json(name = "jwtCredential")
    val jwtCredential: kotlin.String? = null,

    /* Issuer DID of the verifiable credential object. */
    @Json(name = "issuingDID")
    val issuingDID: kotlin.String? = null

)

