/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.IssueCredentialRecord

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param self A string field containing the URL of the current API endpoint
 * @param kind A string field containing the URL of the current API endpoint
 * @param pageOf A string field indicating the type of resource that the contents field contains
 * @param next An optional string field containing the URL of the next page of results. If the API response does not contain any more pages, this field should be set to None.
 * @param previous An optional string field containing the URL of the previous page of results. If the API response is the first page of results, this field should be set to None.
 * @param contents A sequence of IssueCredentialRecord objects representing the list of credential records that the API response contains
 */


data class IssueCredentialRecordPage (

    /* A string field containing the URL of the current API endpoint */
    @Json(name = "self")
    val self: kotlin.String,

    /* A string field containing the URL of the current API endpoint */
    @Json(name = "kind")
    val kind: kotlin.String,

    /* A string field indicating the type of resource that the contents field contains */
    @Json(name = "pageOf")
    val pageOf: kotlin.String,

    /* An optional string field containing the URL of the next page of results. If the API response does not contain any more pages, this field should be set to None. */
    @Json(name = "next")
    val next: kotlin.String? = null,

    /* An optional string field containing the URL of the previous page of results. If the API response is the first page of results, this field should be set to None. */
    @Json(name = "previous")
    val previous: kotlin.String? = null,

    /* A sequence of IssueCredentialRecord objects representing the list of credential records that the API response contains */
    @Json(name = "contents")
    val contents: kotlin.collections.List<IssueCredentialRecord>? = null

)

