/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param did A managed DID
 * @param status A status indicating a publication state of a DID in the wallet (e.g. PUBLICATION_PENDING, PUBLISHED). Does not represent DID a full lifecyle (e.g. deactivated, recovered, updated).
 * @param longFormDid A long-form DID. Mandatory when status is not PUBLISHED and optional when status is PUBLISHED
 */


data class ManagedDID (

    /* A managed DID */
    @Json(name = "did")
    val did: kotlin.String,

    /* A status indicating a publication state of a DID in the wallet (e.g. PUBLICATION_PENDING, PUBLISHED). Does not represent DID a full lifecyle (e.g. deactivated, recovered, updated). */
    @Json(name = "status")
    val status: kotlin.String,

    /* A long-form DID. Mandatory when status is not PUBLISHED and optional when status is PUBLISHED */
    @Json(name = "longFormDid")
    val longFormDid: kotlin.String? = null

)

