/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.Purpose

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * key-pair template to add to DID document.
 *
 * @param id Identifier of a verification material in the DID Document
 * @param purpose 
 */


data class ManagedDIDKeyTemplate (

    /* Identifier of a verification material in the DID Document */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "purpose")
    val purpose: Purpose

)

