/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.PresentationStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param self The reference to the presentation collection itself.
 * @param kind The type of object returned. In this case a `Collection`.
 * @param pageOf Page number within the context of paginated response.
 * @param contents A sequence of Presentation objects.
 * @param next URL of the next page (if available)
 * @param previous URL of the previous page (if available)
 */


data class PresentationStatusPage (

    /* The reference to the presentation collection itself. */
    @Json(name = "self")
    val self: kotlin.String,

    /* The type of object returned. In this case a `Collection`. */
    @Json(name = "kind")
    val kind: kotlin.String,

    /* Page number within the context of paginated response. */
    @Json(name = "pageOf")
    val pageOf: kotlin.String,

    /* A sequence of Presentation objects. */
    @Json(name = "contents")
    val contents: kotlin.collections.List<PresentationStatus>? = null,

    /* URL of the next page (if available) */
    @Json(name = "next")
    val next: kotlin.String? = null,

    /* URL of the previous page (if available) */
    @Json(name = "previous")
    val previous: kotlin.String? = null

)

