/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaId The unique identifier of a schema the VC should comply with.
 * @param trustIssuers One or more issuers that are trusted by the verifier emitting the proof presentation request.
 */


data class ProofRequestAux (

    /* The unique identifier of a schema the VC should comply with. */
    @Json(name = "schemaId")
    val schemaId: kotlin.String,

    /* One or more issuers that are trusted by the verifier emitting the proof presentation request. */
    @Json(name = "trustIssuers")
    val trustIssuers: kotlin.collections.List<kotlin.String>? = null

)

