/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kty 
 * @param crv 
 * @param x 
 * @param y 
 */


data class PublicKeyJwk (

    @Json(name = "kty")
    val kty: kotlin.String,

    @Json(name = "crv")
    val crv: kotlin.String? = null,

    @Json(name = "x")
    val x: kotlin.String? = null,

    @Json(name = "y")
    val y: kotlin.String? = null

)

