/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param action The action to perform on the proof presentation record.
 * @param proofId The unique identifier of the issue credential record - and hence VC - to use as the prover accepts the presentation request. Only applicable on the prover side when the action is `request-accept`.
 */


data class RequestPresentationAction (

    /* The action to perform on the proof presentation record. */
    @Json(name = "action")
    val action: RequestPresentationAction.Action,

    /* The unique identifier of the issue credential record - and hence VC - to use as the prover accepts the presentation request. Only applicable on the prover side when the action is `request-accept`. */
    @Json(name = "proofId")
    val proofId: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * The action to perform on the proof presentation record.
     *
     * Values: requestMinusAccept,requestMinusReject,presentationMinusAccept,presentationMinusReject
     */
    @JsonClass(generateAdapter = false)
    enum class Action(val value: kotlin.String) {
        @Json(name = "request-accept") requestMinusAccept("request-accept"),
        @Json(name = "request-reject") requestMinusReject("request-reject"),
        @Json(name = "presentation-accept") presentationMinusAccept("presentation-accept"),
        @Json(name = "presentation-reject") presentationMinusReject("presentation-reject");
    }
}

