/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param presentationId Ref to the id on the presentation (db ref)
 */


data class RequestPresentationOutput (

    /* Ref to the id on the presentation (db ref) */
    @Json(name = "presentationId")
    val presentationId: kotlin.String

)

