/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.Options
import io.iohk.atala.prism.models.ProofRequestAux

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param connectionId The unique identifier of an established connection between the verifier and the prover.
 * @param options 
 * @param proofs The type of proofs requested in the context of this proof presentation request (e.g., VC schema, trusted issuers, etc.)
 */


data class RequestPresentationInput (

    /* The unique identifier of an established connection between the verifier and the prover. */
    @Json(name = "connectionId")
    val connectionId: kotlin.String,

    @Json(name = "options")
    val options: Options? = null,

    /* The type of proofs requested in the context of this proof presentation request (e.g., VC schema, trusted issuers, etc.) */
    @Json(name = "proofs")
    val proofs: kotlin.collections.List<ProofRequestAux>? = null

)

