/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A service expressed in the DID document. https://www.w3.org/TR/did-core/#services
 *
 * @param id The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID
 * @param type Service type. Can contain multiple possible values as described in the [Create DID operation](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md#create-did) under the construction section.
 * @param serviceEndpoint The service endpoint. Can contain multiple possible values as described in the [Create DID operation]
 */


data class Service (

    /* The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID */
    @Json(name = "id")
    val id: kotlin.String,

    /* Service type. Can contain multiple possible values as described in the [Create DID operation](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md#create-did) under the construction section. */
    @Json(name = "type")
    val type: kotlin.String,

    /* The service endpoint. Can contain multiple possible values as described in the [Create DID operation] */
    @Json(name = "serviceEndpoint")
    val serviceEndpoint: kotlin.collections.List<kotlin.String>

)

