/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A patch to existing Service. 'type' and 'serviceEndpoint' cannot both be empty.
 *
 * @param id The id of the service to update
 * @param type The type of the service
 * @param serviceEndpoint 
 */


data class UpdateManagedDIDServiceAction (

    /* The id of the service to update */
    @Json(name = "id")
    val id: kotlin.String,

    /* The type of the service */
    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "serviceEndpoint")
    val serviceEndpoint: kotlin.collections.List<kotlin.String>? = null

)

