/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.ActionType
import io.iohk.atala.prism.models.ManagedDIDKeyTemplate
import io.iohk.atala.prism.models.RemoveEntryById
import io.iohk.atala.prism.models.Service
import io.iohk.atala.prism.models.UpdateManagedDIDServiceAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A list of actions to perform on DID document. The field `addKey`, `removeKey`, `addService`, `removeService`, `updateService` must corresponds to the `actionType` specified. For example, `addKey` must be present when `actionType` is `ADD_KEY`.
 *
 * @param actionType 
 * @param addKey 
 * @param removeKey 
 * @param addService 
 * @param removeService 
 * @param updateService 
 */


data class UpdateManagedDIDRequestAction (

    @Json(name = "actionType")
    val actionType: ActionType,

    @Json(name = "addKey")
    val addKey: ManagedDIDKeyTemplate? = null,

    @Json(name = "removeKey")
    val removeKey: RemoveEntryById? = null,

    @Json(name = "addService")
    val addService: Service? = null,

    @Json(name = "removeService")
    val removeService: RemoveEntryById? = null,

    @Json(name = "updateService")
    val updateService: UpdateManagedDIDServiceAction? = null

)

