/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.VerificationPolicyConstraint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param self 
 * @param kind 
 * @param id 
 * @param nonce 
 * @param name 
 * @param description 
 * @param createdAt 
 * @param updatedAt 
 * @param constraints 
 */


data class VerificationPolicy (

    @Json(name = "self")
    val self: kotlin.String,

    @Json(name = "kind")
    val kind: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "nonce")
    val nonce: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "constraints")
    val constraints: kotlin.collections.List<VerificationPolicyConstraint>? = null

)

