/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaId 
 * @param trustedIssuers 
 */


data class VerificationPolicyConstraint (

    @Json(name = "schemaId")
    val schemaId: kotlin.String,

    @Json(name = "trustedIssuers")
    val trustedIssuers: kotlin.collections.List<kotlin.String>? = null

)

