/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.iohk.atala.prism.models

import io.iohk.atala.prism.models.PublicKeyJwk

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A cryptographic public key expressed in the DID document. https://www.w3.org/TR/did-core/#verification-methods
 *
 * @param id The identifier for the verification method.
 * @param type The type of the verification method.
 * @param controller The DID that controls the verification method.
 * @param publicKeyJwk 
 */


data class VerificationMethod (

    /* The identifier for the verification method. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The type of the verification method. */
    @Json(name = "type")
    val type: kotlin.String,

    /* The DID that controls the verification method. */
    @Json(name = "controller")
    val controller: kotlin.String,

    @Json(name = "publicKeyJwk")
    val publicKeyJwk: PublicKeyJwk

)

