# coding: utf-8

"""
    Prism Agent

    No description provided

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "open-enterprise-agent-python-client"
VERSION = "0.0.1"

REQUIRES = [
    "certifi >= 14.5.14",
    "frozendict ~= 2.3.4",
    "python-dateutil ~= 2.7.0",
    "setuptools >= 21.0.0",
    "typing_extensions ~= 4.3.0",
    "urllib3 ~= 1.26.7",
]

setup(
    name=NAME,
    version=VERSION,
    description="Prism Agent Client",
    author="Allain Magyar",
    author_email="",
    url="https://github.com/hyperledger-labs/open-enterprise-agent",
    keywords=["Prism Agent"],
    python_requires=">=3.7",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Prism-agent models generated from OpenAPI Specification
    """
)
