@startuml
autonumber

participant "Verifiable\nData Registry" as L
participant "Schema Publisher" as SP
participant Issuer as I
participant Holder as H

Note over L, H: Schema Publisher: Publish Schema

SP ->> L: Publish Schema (Schema)
L ->> I: Schema ID,\nSchema Transaction ID
Note over L, SP #pink: schema = issuerId, name, version, attribute names \n**issuerId MUST adhere to Issuer identifiers rules**
Note over L, SP #pink: **Schema ID** defined by the used AnonCreds method
/ Note over H #pink: 💡The "Verifier" role is\nomitted in this diagram, \nsince it is not required\nfor the setup

Note over L, H: Issuer: Create, Store and Publish CredDef

I ->> I: create_and_store_credential_def\n(Schema, tag, support_revocation)
Note right of I: store public /\nprivate keys and\n correctness proof
I ->> L: Publish CredDef (CredDef)

Note over L, H: Issuer: Create, Store and Publish Revocation Registry (Optional)

I ->> I: create_and_store_revoc_reg (intCredDef)
Note right of I: get keys
Note right of I: store revoc_reg_def,\nrevoc_reg_accum,\npriv_key,\ntails_generator
I ->> L: Publish RevReg \n(revoc_reg_id,\nrevoc_reg_def_json,\nrevoc_reg_entry_json)

Note over L, H: Holder: Create and Store Link Secret

H ->> H: anoncreds_prover_create_link_secret
H ->> H: store link secret

note over H #pink: 💡**AnonCreds method** defines \nthe identifier for published \nobjects and where those objects\n are published (specific VDR), \nin the similar way to DID methods.
@enduml
