@startuml
title Issue flow - AnonCreds

actor Holder as holder
participant "Holder Cloud Agent" as holderAgent
participant VDR
participant "Issuer Cloud Agent" as issuerAgent
actor Issuer as issuer

note over holderAgent, issuerAgent #aqua
    It is assumed that a connection already exists between the holder and the issuer.
    It is also assumed that the AnonCreds related setup is completed (Link Secret + Schema + Credential Definition created).
end note
|||
== Create and send credential offer ==
|||
issuer -> issuerAgent: Create new credential offer\n""POST /issue-credentials/credential-offers""\n""{format, connectionId, claims, credDefId}""
issuerAgent -> VDR: Fetch JSON Schema
issuerAgent -> issuerAgent: Verify provided claims against schema
issuerAgent -> issuerAgent: Create issue credential state record
issuerAgent --> issuer: Issue credential record {id, state}
note over issuerAgent: state=OfferPending
|||

== Send credential offer over DIDComm ==
|||
issuerAgent -> holderAgent: ""CredentialOffer"" message
holderAgent -> holderAgent: Create issue credential state record
holderAgent --> issuerAgent: OK
note over holderAgent: state=OfferReceived
/ note over issuerAgent: state=OfferSent
|||

== Review and accept credential offer ==
|||
holder -> holderAgent: Retrieve credential records\n""GET /issue-credentials/records""
holderAgent --> holder: record list
|||
holder -> holderAgent: Accept credential offer\n""POST /issue-credentials/records/{id}/accept-offer""\n""{}""
holderAgent --> holder: OK
note over holderAgent: state=RequestPending
|||

== Generate and send credential request ==
|||
holderAgent -> VDR: Fetch Credential Definition
holderAgent -> holderAgent: Load Link Secret
holderAgent -> holderAgent: Create credential request (input: link secret, cred def, offer)
holderAgent -> holderAgent: Store request metadata
note over holderAgent: state=RequestGenerated
|||
holderAgent -> issuerAgent: RequestCredential message (includes blinded link secret)
issuerAgent --> holderAgent: OK
note over holderAgent: state=RequestSent
/ note over issuerAgent: state=RequestReceived
|||

== Generate and send credential ==
|||
alt automaticIssuance=true
issuerAgent -> issuerAgent: Automatically approve credential request
else automaticIssuance=false
issuer -> issuerAgent: Explicitly approve credential request\n""POST /issue-credentials/records/{id}/issue-credential""
end
note over issuerAgent: state=CredentialPending
|||
issuerAgent -> issuerAgent: Generate credential signed with credential definition keys\nand issued to the Holder's blinded link secret
note over issuerAgent: state=CredentialGenerated
|||
issuerAgent -> holderAgent: ""IssueCredential"" message (includes AnonCreds credential)
holderAgent -> VDR: Fetch Credential Definition
holderAgent -> holderAgent: process/verify credential (input: credential, request metadata, link secret, cred def)
holderAgent -> holderAgent: Store credential
holderAgent --> issuerAgent: OK
note over issuerAgent: state=CredentialSent
/ note over holderAgent: state=CredentialReceived
|||
@enduml
